# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestCreateFeedBack():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()

    def test_createfeedback(self):
        self.driver.get("http://192.168.10.13:8080/")
        time.sleep(2)
        self.driver.maximize_window()
        self.driver.find_element(By.CSS_SELECTOR, "#app > div > footer > div > button").click()
        self.driver.execute_script("window.scrollBy(0, 2800);")
        self.driver.find_element(By.XPATH, "//section[@id=\'registration\']/div/div/div/div[2]/div/div/div/input").click()
        self.driver.find_element(By.XPATH, "//section[@id=\'registration\']/div/div/div/div[2]/div/div/div/input").send_keys("12345")
        self.driver.find_element(By.CSS_SELECTOR, ".v-input--is-focused .v-input__slot").click()
        self.driver.find_element(By.XPATH, "//section[@id=\'registration\']/div/div/div/div[5]/div/div/div/input").send_keys("12456")
        self.driver.find_element(By.XPATH, "//section[@id=\'registration\']/div/div/div/div[14]/div/div/div/textarea").click()
        self.driver.find_element(By.XPATH, "//section[@id=\'registration\']/div/div/div/div[14]/div/div/div/textarea").send_keys("12345")
        self.driver.find_element(By.XPATH, "//button[contains(.,\'Оставить заявку\')]").click()
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".v-card__title")))
        self.driver.find_element(By.XPATH, "//button[contains(.,\'Ок\')]").click()
        time.sleep(5)
        self.driver.close()