# Generated by Selenium IDE
import time

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options


class TestTestCase():
    def setup_method(self):
        options = webdriver.ChromeOptions()
        options.add_argument("maximized")
        self.driver = webdriver.Chrome(options=options)
        self.vars = {}

    def teardown_method(self):
        self.driver.quit()

    def test_testCase(self):
        # Test name: TestCase
        # Step # | name | target | value
        # 1 | open | https://outstaff.bls-soft.ru/ |
        self.driver.get("https://outstaff.bls-soft.ru/")
        time.sleep(1)
        # 2 | click | linkText=Сформировать команду |
        self.driver.find_element(By.LINK_TEXT, "Сформировать команду").click()
        print("Тест пройден успешно")

x = TestTestCase()
x.setup_method()
x.test_testCase()

